
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: esportify_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://esportify_user:esportify_pass@db:3306/esportify?serverVersion=8.0&charset=utf8mb4"
    command: >
      bash -c "
        php bin/console doctrine:database:create --if-not-exists &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php bin/console doctrine:fixtures:load --no-interaction &&
        php bin/console cache:clear &&
        apache2-foreground
        "

  db:
    image: mysql:8.0
    container_name: esportify_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esportify
      MYSQL_USER: esportify_user
      MYSQL_PASSWORD: esportify_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: esportify_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  
volumes:
  db_data: