# Page d'accueil
app_home:
  path: /
  controller: App\Controller\HomeController::index

# Page Events
events:
  path: /events
  controller: App\Controller\EventsController::index
  methods: [GET]

# Page Contact
contact:
  path: /contact
  controller: App\Controller\ContactController::index
  methods: [GET, POST]

# Formulaires
signup_form:
  path: /signup
  controller: App\Controller\AuthController::signup
  methods: [GET]

app_register:
  path: /signup/submit
  controller: App\Controller\RegisterController::register
  methods: [POST]

event_create:
  path: /events/create
  controller: App\Controller\CreateEventController::create
  methods: [GET, POST]

# Connexion et Déconnexion
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: [GET]

# Espaces Utilisateurs
player_space:
  path: /player_space
  controller: App\Controller\SpaceController::playerSpace
  methods: [GET]

organizer_space:
  path: /organizer_space
  controller: App\Controller\SpaceController::organizerSpace
  methods: [GET]

admin_dashboard:
  path: /admin_dashboard
  controller: App\Controller\SpaceController::adminDashboard
  methods: [GET]

# Espaces à venir
forgot_password:
  path: /forgot_password
  controller: App\Controller\AuthController::forgotPassword

modifProfile:
  path: /modifProfile
  controller: App\Controller\AuthController::modifProfile

# Mentions légales
cgu:
  path: /cgu
  controller: App\Controller\LegalController::cgu
  methods: [GET]

legal_mentions:
  path: /mentions-legales
  controller: App\Controller\LegalController::legalMentions
  methods: [GET]

privacy:
  path: /confidentialite
  controller: App\Controller\LegalController::privacy
  methods: [GET]
