# Page d'accueil
app_home:
  path: /
  controller: App\Controller\HomeController::index

# Page Events
events:
  path: /events
  controller: App\Controller\EventsController::index
  methods: [GET]

add_favorite_event:
  path: /favorite/event/add/{tournamentId}
  controller: App\Controller\FavoriteEventController::addFavoriteEvent  
  methods: [GET]

remove_favorite_event:
  path: /favorite/event/remove/{tournamentId}
  controller: App\Controller\FavoriteEventController::removeFavoriteEvent  
  methods: [GET]

# Formulaires
contact:
  path: /contact
  controller: App\Controller\ContactController::index
  methods: [GET, POST]

signup_form:
  path: /signup
  controller: App\Controller\AuthController::signup
  methods: [GET]

app_register:
  path: /signup/submit
  controller: App\Controller\RegisterController::register
  methods: [POST]

event_create:
  path: /events/create
  controller: App\Controller\CreateEventController::create
  methods: [GET, POST]

# Connexion et Déconnexion
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: [GET]

# Espaces Utilisateurs
player_space:
  path: /player_space
  controller: App\Controller\SpaceController::playerSpace
  methods: [GET]

organizer_space:
  path: /organizer_space
  controller: App\Controller\SpaceController::organizerSpace
  methods: [GET, POST]

admin_dashboard:
  path: /admin_dashboard
  controller: App\Controller\AdminTournamentRequestController::index
  methods: [GET]

# Demandes Utilisateurs et validation

admin_tournament_show:
  path: /admin/tournament/show/{id}
  controller: App\Controller\AdminTournamentRequestController::show
  methods: [GET]

admin_tournament_validate:
  path: /admin/tournament/validate/{id}
  controller: App\Controller\AdminTournamentRequestController::validate
  methods: [POST]

admin_tournament_refuse:
  path: /admin/tournament/refuse/{id}
  controller: App\Controller\AdminTournamentRequestController::refuse
  methods: [POST]

# Espaces à venir
forgot_password:
  path: /forgot_password
  controller: App\Controller\AuthController::forgotPassword

modifProfile:
  path: /modifProfile
  controller: App\Controller\AuthController::modifProfile

# Mentions légales
cgu:
  path: /cgu
  controller: App\Controller\LegalController::cgu
  methods: [GET]

legal_mentions:
  path: /mentions-legales
  controller: App\Controller\LegalController::legalMentions
  methods: [GET]

privacy:
  path: /confidentialite
  controller: App\Controller\LegalController::privacy
  methods: [GET]

# Events valide JSON
api_events:
  path: api/events
  controller: App\Controller\Api\EventApiController::index
  methods: [GET]

# Mise à jour automatique des statuts de tournois (cron)
admin_update_tournament_status:
  path: /admin/update-tournaments-status
  controller: App\Controller\TournamentStatusUpdateController::update
  methods: [GET, POST]