app_home:
  path: /
  controller: App\Controller\HomeController::index

events:
  path: /events
  controller: App\Controller\EventsController::index
  methods: [GET]

contact:
  path: /contact
  controller: App\Controller\ContactController::index

signup:
  path: /signup
  controller: App\Controller\AuthController::signup

forgot_password:
  path: /forgot-password
  controller: App\Controller\AuthController::forgotPassword

modifProfile:
  path: /modifProfile
  controller: App\Controller\AuthController::modifProfile

player_space:
  path: /player-space
  controller: App\Controller\SpaceController::playerSpace

organizer_space:
  path: /organizer-space
  controller: App\Controller\SpaceController::organizerSpace

admin_dashboard:
  path: /admin-dashboard
  controller: App\Controller\SpaceController::adminDashboard

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  